import React from 'react';
import {
  Activity,
  ArrowLeft,
  ArrowRight,
  Camera,
  CircleCheckBig,
  CircleHelp,
  ClipboardCopy,
  Clock3,
  Cloud,
  Delete,
  DoorClosed,
  DoorOpen,
  HardDrive,
  House,
  KeyRound,
  LoaderCircle,
  MonitorCog,
  PackageOpen,
  PackagePlus,
  Play,
  QrCode,
  RefreshCw,
  ShieldCheck,
  TriangleAlert,
  Volume2,
  VolumeX,
  Wifi,
  X,
} from 'lucide-react';

const DEFAULT_ICON_PROPS = {
  'aria-hidden': true,
  focusable: 'false',
  strokeWidth: 2.2,
};

export function KioskIcon({ icon: Icon, ...props }) {
  return <Icon {...DEFAULT_ICON_PROPS} {...props} />;
}

export const KioskIcons = {
  activity: Activity,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  camera: Camera,
  clipboard: ClipboardCopy,
  cloud: Cloud,
  check: CircleCheckBig,
  close: X,
  clock: Clock3,
  courier: PackagePlus,
  delete: Delete,
  door: DoorOpen,
  doorClosed: DoorClosed,
  hardDrive: HardDrive,
  help: CircleHelp,
  home: House,
  key: KeyRound,
  loading: LoaderCircle,
  monitor: MonitorCog,
  play: Play,
  qr: QrCode,
  refresh: RefreshCw,
  resident: PackageOpen,
  shield: ShieldCheck,
  warning: TriangleAlert,
  volume: Volume2,
  volumeMuted: VolumeX,
  wifi: Wifi,
};
